/**
 * Regenerates `content/image-sizes.ts`.
 *
 * `next.config.ts` sets `images.unoptimized`, so next/image cannot infer
 * intrinsic dimensions itself and guessing one aspect ratio per slot crops wide
 * spreads. Run `npm run sizes` after adding, replacing or recropping artwork.
 */
import sharp from 'sharp'
import { readdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const IMAGES = path.join(ROOT, 'public', 'images')

async function walk(dir) {
  const out = []
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name)
    if (e.isDirectory()) out.push(...(await walk(p)))
    else if (/\.(jpe?g|png|webp|avif)$/i.test(e.name)) out.push(p)
  }
  return out
}

const files = (await walk(IMAGES)).sort()
const rows = []
for (const f of files) {
  const { width, height } = await sharp(f).metadata()
  const src = '/' + path.relative(path.join(ROOT, 'public'), f).split(path.sep).join('/')
  rows.push(`  '${src}': { width: ${width}, height: ${height} },`)
}

const body = `/**
 * Intrinsic dimensions of every published image.
 *
 * GENERATED by \`npm run sizes\` — do not edit by hand.
 * \`next.config.ts\` sets \`images.unoptimized\`, so next/image cannot infer
 * these itself, and guessing one aspect ratio per slot crops wide spreads.
 */

export const imageSizes: Record<string, { width: number; height: number }> = {
${rows.join('\n')}
}

/** Falls back to a 3:2 box for anything not in the manifest. */
export const sizeOf = (src: string) => imageSizes[src] ?? { width: 1500, height: 1000 }
`

await writeFile(path.join(ROOT, 'content', 'image-sizes.ts'), body, 'utf8')
console.log(`${rows.length} images written to content/image-sizes.ts`)
